package com.ossez.openai.edit;


/**
 * An edit generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */

public class EditChoice {

    /**
     * The edited text.
     */
    String text;

    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }
}
